version: '3.8' # Use a suitable version for your needs
services:
  omnitool:
    image: manusapiens/omnitool_metal_pi:latest
    ports:
      - "1688:4444"
    volumes:
      - "./omnitool.data/file-import:/app/omnitool/packages/omni-server/data.local/file-import"
      - "./omnitool.data/file-export:/app/omnitool/packages/omni-server/data.local/file-export"
    restart: unless-stopped
